name: Snowflake_CI/CD_Workflow

on:
  push:
    branches:
      - dev
      - qa
      - uat
      - main  # Assume main is for PROD
  pull_request:
    branches:
      - dev
      - qa
      - uat
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [DEV, QA, UAT, PROD]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Snowflake Connector for Python
        run: |
          pip install snowflake-connector-python

      - name: Set environment variables
        run: echo "ENVIRONMENT=${{ matrix.environment }}" >> $GITHUB_ENV

      - name: Run SQL Scripts on Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets['SNOWFLAKE_ACCOUNT_' + env.ENVIRONMENT] }}
          SNOWFLAKE_USER: ${{ secrets['SNOWFLAKE_USER_' + env.ENVIRONMENT] }}
          SNOWFLAKE_PASSWORD: ${{ secrets['SNOWFLAKE_PASSWORD_' + env.ENVIRONMENT] }}
          SNOWFLAKE_DATABASE: ${{ secrets['SNOWFLAKE_DATABASE_' + env.ENVIRONMENT] }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets['SNOWFLAKE_WAREHOUSE_' + env.ENVIRONMENT] }}
          SNOWFLAKE_SCHEMA: ${{ secrets['SNOWFLAKE_SCHEMA_' + env.ENVIRONMENT] }}
        run: |
          python -c "
import snowflake.connector

# Create a connection to Snowflake
ctx = snowflake.connector.connect(
    user='$SNOWFLAKE_USER',
    password='$SNOWFLAKE_PASSWORD',
    account='$SNOWFLAKE_ACCOUNT',
    warehouse='$SNOWFLAKE_WAREHOUSE',
    database='$SNOWFLAKE_DATABASE',
    schema='$SNOWFLAKE_SCHEMA'
)

# Create a cursor
cs = ctx.cursor()

# Run your SQL scripts here
try:
    with open('path/to/your/script.sql', 'r') as file:
        sql_script = file.read()
    cs.execute(sql_script)
finally:
    cs.close()
    ctx.close()
          "
