name: Snowflake_CICD_Workflow

on:
  pull_request:
    types: [closed]
    branches: [DEV]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Check Python version
        run: python --version

      - name: Install Snowflake Connector for Python
        run: |
          pip install snowflake-connector-python

      - name: Run SQL Scripts on Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SF_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SF_SCHEMA }}
        run: |
          python python_scripts/snowflake_deployment.py
